version: '3'
services:
  nextcloud:
    image: nextcloud
    ports:
      - 3013:80
    volumes:
      - nextcloud_data:/var/www/html
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=gudpassword
      - NEXTCLOUD_ADMIN_USER=root
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.bearkillerpt.xyz
      - NEXTCLOUD_OVERWRITEPROTOCOL=https

  db:
    image: biarms/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gudpassword
      - MYSQL_PASSWORD=gudpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data
    restart: unless-stopped

volumes:
  nextcloud_data:
  db_data:
  redis_data:
 
